### ISSUE TITLE
Feeback

### ISSUE THREAD

**Issue by ggwpez** [mittal-parth/polkadot-dev-cli#7]
Thanks for creating this 😄 Some random feedback points in no particular order:

- [x] Running the command without any sub-command should print some inviting hello message instead of an error. Just basic intro into what Polkadot is and things for developers to do. You can also placeholder this and I provide some concrete text.
- [x] The sub-commands should print the steps that they are doing, so that devs understand what is happening under the hood. For example when running `format`, it should print what commands it is using to format the rust and toml files, markdown... etc

**Comment by mittal-parth** [comment]
Got it, sounds good!

**Comment by mittal-parth** [comment]
Hi @ggwpez!

Implemented these changes in #8 

Examples are also included in the PR :)

Thanks again!

**Comment by ggwpez** [comment]
Very nice, thanks! Am back from holiday, so will check it out now :)
